name: Tested on Testnet
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  check-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: |
            testnet-pass
            testnet-skip
